/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PatchStepDataDto = {
  /**
   * New name for the step
   */
  name?: string | undefined;
  /**
   * Control values for the step
   */
  controlValues?: { [k: string]: any } | null | undefined;
};

/** @internal */
export const PatchStepDataDto$inboundSchema: z.ZodType<
  PatchStepDataDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  controlValues: z.nullable(z.record(z.any())).optional(),
});

/** @internal */
export type PatchStepDataDto$Outbound = {
  name?: string | undefined;
  controlValues?: { [k: string]: any } | null | undefined;
};

/** @internal */
export const PatchStepDataDto$outboundSchema: z.ZodType<
  PatchStepDataDto$Outbound,
  z.ZodTypeDef,
  PatchStepDataDto
> = z.object({
  name: z.string().optional(),
  controlValues: z.nullable(z.record(z.any())).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchStepDataDto$ {
  /** @deprecated use `PatchStepDataDto$inboundSchema` instead. */
  export const inboundSchema = PatchStepDataDto$inboundSchema;
  /** @deprecated use `PatchStepDataDto$outboundSchema` instead. */
  export const outboundSchema = PatchStepDataDto$outboundSchema;
  /** @deprecated use `PatchStepDataDto$Outbound` instead. */
  export type Outbound = PatchStepDataDto$Outbound;
}

export function patchStepDataDtoToJSON(
  patchStepDataDto: PatchStepDataDto,
): string {
  return JSON.stringify(
    PatchStepDataDto$outboundSchema.parse(patchStepDataDto),
  );
}

export function patchStepDataDtoFromJSON(
  jsonString: string,
): SafeParseResult<PatchStepDataDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchStepDataDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchStepDataDto' from JSON`,
  );
}
