/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { NovuCore } from "../core.js";
import { workflowsStepsPatch } from "../funcs/workflowsStepsPatch.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useNovuContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type WorkflowsStepsPatchMutationVariables = {
  request: operations.WorkflowControllerPatchWorkflowStepDataRequest;
  options?: RequestOptions;
};

export type WorkflowsStepsPatchMutationData =
  operations.WorkflowControllerPatchWorkflowStepDataResponse;

/**
 * Patch workflow step data
 *
 * @remarks
 * Partially updates data for a specific step in a workflow
 */
export function useWorkflowsStepsPatchMutation(
  options?: MutationHookOptions<
    WorkflowsStepsPatchMutationData,
    Error,
    WorkflowsStepsPatchMutationVariables
  >,
): UseMutationResult<
  WorkflowsStepsPatchMutationData,
  Error,
  WorkflowsStepsPatchMutationVariables
> {
  const client = useNovuContext();
  return useMutation({
    ...buildWorkflowsStepsPatchMutation(client, options),
    ...options,
  });
}

export function mutationKeyWorkflowsStepsPatch(): MutationKey {
  return ["@novu/api", "Steps", "patch"];
}

export function buildWorkflowsStepsPatchMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: WorkflowsStepsPatchMutationVariables,
  ) => Promise<WorkflowsStepsPatchMutationData>;
} {
  return {
    mutationKey: mutationKeyWorkflowsStepsPatch(),
    mutationFn: function workflowsStepsPatchMutationFn({
      request,
      options,
    }): Promise<WorkflowsStepsPatchMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(workflowsStepsPatch(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
