/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type WorkflowControllerPatchWorkflowStepDataRequest = {
  workflowId: string;
  stepId: string;
  /**
   * A header for idempotency purposes
   */
  idempotencyKey?: string | undefined;
  /**
   * Step data patch details
   */
  patchStepDataDto: components.PatchStepDataDto;
};

export type WorkflowControllerPatchWorkflowStepDataResponse = {
  headers: { [k: string]: Array<string> };
  result: components.StepResponseDto;
};

/** @internal */
export const WorkflowControllerPatchWorkflowStepDataRequest$inboundSchema:
  z.ZodType<
    WorkflowControllerPatchWorkflowStepDataRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    workflowId: z.string(),
    stepId: z.string(),
    "idempotency-key": z.string().optional(),
    PatchStepDataDto: components.PatchStepDataDto$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "idempotency-key": "idempotencyKey",
      "PatchStepDataDto": "patchStepDataDto",
    });
  });

/** @internal */
export type WorkflowControllerPatchWorkflowStepDataRequest$Outbound = {
  workflowId: string;
  stepId: string;
  "idempotency-key"?: string | undefined;
  PatchStepDataDto: components.PatchStepDataDto$Outbound;
};

/** @internal */
export const WorkflowControllerPatchWorkflowStepDataRequest$outboundSchema:
  z.ZodType<
    WorkflowControllerPatchWorkflowStepDataRequest$Outbound,
    z.ZodTypeDef,
    WorkflowControllerPatchWorkflowStepDataRequest
  > = z.object({
    workflowId: z.string(),
    stepId: z.string(),
    idempotencyKey: z.string().optional(),
    patchStepDataDto: components.PatchStepDataDto$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      idempotencyKey: "idempotency-key",
      patchStepDataDto: "PatchStepDataDto",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WorkflowControllerPatchWorkflowStepDataRequest$ {
  /** @deprecated use `WorkflowControllerPatchWorkflowStepDataRequest$inboundSchema` instead. */
  export const inboundSchema =
    WorkflowControllerPatchWorkflowStepDataRequest$inboundSchema;
  /** @deprecated use `WorkflowControllerPatchWorkflowStepDataRequest$outboundSchema` instead. */
  export const outboundSchema =
    WorkflowControllerPatchWorkflowStepDataRequest$outboundSchema;
  /** @deprecated use `WorkflowControllerPatchWorkflowStepDataRequest$Outbound` instead. */
  export type Outbound =
    WorkflowControllerPatchWorkflowStepDataRequest$Outbound;
}

export function workflowControllerPatchWorkflowStepDataRequestToJSON(
  workflowControllerPatchWorkflowStepDataRequest:
    WorkflowControllerPatchWorkflowStepDataRequest,
): string {
  return JSON.stringify(
    WorkflowControllerPatchWorkflowStepDataRequest$outboundSchema.parse(
      workflowControllerPatchWorkflowStepDataRequest,
    ),
  );
}

export function workflowControllerPatchWorkflowStepDataRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  WorkflowControllerPatchWorkflowStepDataRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      WorkflowControllerPatchWorkflowStepDataRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'WorkflowControllerPatchWorkflowStepDataRequest' from JSON`,
  );
}

/** @internal */
export const WorkflowControllerPatchWorkflowStepDataResponse$inboundSchema:
  z.ZodType<
    WorkflowControllerPatchWorkflowStepDataResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())),
    Result: components.StepResponseDto$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  });

/** @internal */
export type WorkflowControllerPatchWorkflowStepDataResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.StepResponseDto$Outbound;
};

/** @internal */
export const WorkflowControllerPatchWorkflowStepDataResponse$outboundSchema:
  z.ZodType<
    WorkflowControllerPatchWorkflowStepDataResponse$Outbound,
    z.ZodTypeDef,
    WorkflowControllerPatchWorkflowStepDataResponse
  > = z.object({
    headers: z.record(z.array(z.string())),
    result: components.StepResponseDto$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      headers: "Headers",
      result: "Result",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WorkflowControllerPatchWorkflowStepDataResponse$ {
  /** @deprecated use `WorkflowControllerPatchWorkflowStepDataResponse$inboundSchema` instead. */
  export const inboundSchema =
    WorkflowControllerPatchWorkflowStepDataResponse$inboundSchema;
  /** @deprecated use `WorkflowControllerPatchWorkflowStepDataResponse$outboundSchema` instead. */
  export const outboundSchema =
    WorkflowControllerPatchWorkflowStepDataResponse$outboundSchema;
  /** @deprecated use `WorkflowControllerPatchWorkflowStepDataResponse$Outbound` instead. */
  export type Outbound =
    WorkflowControllerPatchWorkflowStepDataResponse$Outbound;
}

export function workflowControllerPatchWorkflowStepDataResponseToJSON(
  workflowControllerPatchWorkflowStepDataResponse:
    WorkflowControllerPatchWorkflowStepDataResponse,
): string {
  return JSON.stringify(
    WorkflowControllerPatchWorkflowStepDataResponse$outboundSchema.parse(
      workflowControllerPatchWorkflowStepDataResponse,
    ),
  );
}

export function workflowControllerPatchWorkflowStepDataResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  WorkflowControllerPatchWorkflowStepDataResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      WorkflowControllerPatchWorkflowStepDataResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'WorkflowControllerPatchWorkflowStepDataResponse' from JSON`,
  );
}
